#!/usr/bin/env php
<?php
require_once(__DIR__.'/../yii2-quartronic-demo/vendor/autoload.php');

$Q = new \quarsintex\quartronic\qcore\Quartronic;
$Q->run([
    'route'=>$route,
    'mode'=>'console',
]);